version: "3.9"

services:

  database:
    image: postgres
    container_name: database_sga
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

  testing-database:
    image: postgres
    container_name: test_db_sga
    ports:
      - 5433:5432  # exposed on a different host port
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_db
    volumes:
      - test_pgdata:/data/postgres
  app:
    build: .
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - 8080:8080
    environment:
      - DATABASE=${DATABASE}
      - SECRET=${SECRET}

    links:
      - database
      - testing-database

    depends_on:
      - database
      - testing-database

volumes:
  pgdata:
    driver: local
  test_pgdata:
    driver: local
